version: "3.3"

services:
  # Backend API
  lyntmail-api:
    container_name: backend
    build: .
    environment:
      POSTGRES_URI : postgresql://URI
      PASSWORD : PASSWORD
      PRIVATE_KEY : PRIVATE_KEY
      PUBLIC_KEY: PUBLIC_KEY
    links:
      - postgres
    ports:
      - "3001:3001"
    volumes: 
      - ./:/opt/node_app
      - ./postgres-data:/var/lib/postgresql/data

  # Database
  postgres:
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : PASSWORD
      POSTGRES_DB : lyntmail-db
      POSTGRES_HOST : postgres
    build: ./postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
